top/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='homeTop'),

    path('month/', views.monthTop, name='monthTop'),
    path('month/page-<int:pagenum>/', views.monthTop, name='monthTop'),

    path('year/', views.yearTop, name='yearTop'),
    path('year/page-<int:pagenum>/', views.yearTop, name='yearTop'),

    path('global/', views.globalTop, name='globalTop'),
    path('global/page-<int:pagenum>/', views.globalTop, name='globalTop'),

    path('recent/', views.recentTop, name='recentTop'),
    path('recent/page-<int:pagenum>/', views.recentTop, name='recentTop'),

    path('popular/', views.popularTop, name='popularTop'),
    path('popular/page-<int:pagenum>/', views.popularTop, name='popularTop'),

    path('premium/', views.premium, name='premium'),

    path('servers/search', views.serverSearch, name='serverSearch'),

    path('servers/', views.myServers, name='myServers'),

    path('server/<int:server_id>/', views.server, name='server'),
    path('server/<int:server_id>/edit', views.editServer, name='editServer'),
    path('server/<int:server_id>/vote', views.voteServer, name='voteServer'),
    path('server/<int:server_id>/visit', views.visitServer, name='visitServer'),
    path('server/<int:server_id>/comment', views.commentServer, name='commentServer'),
    path('server/<int:server_id>/stats', views.server_stats, name='server_stats'),
    path('server/<int:server_id>/<slug:slug>/', views.serverWithSlug, name='serverWithSlug'),
    path('server/add', views.addServer, name='addServer'),
]

topserver/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from top.views import contact

urlpatterns = [
    path('', RedirectView.as_view(url='top/', permanent=False)),
    path('top/', include('top.urls')),
    path('contact/', contact, name='contact'),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

top/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from top.models import Server, Comment
from top.widgets import PictureWidget


class ContactForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(), label=_("Email"))
    subject = forms.CharField(widget=forms.TextInput(), label=_("Subject"))
    message = forms.CharField(widget=forms.Textarea(), label=_("Message"))
    captcha = forms.CharField(widget=forms.HiddenInput())


class ServerForm(forms.ModelForm):
    class Meta:
        model = Server
        widgets = {
            'image': PictureWidget(),
        }
        # exclude some fields we don't want the user to modify
        exclude = (
        'notify', 'date', 'owner', 'votes', 'month_votes', 'year_votes', 'online', 'visits', 'conversions', 'premium', 'tags')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # exclude some fields we don't want the user to modify
        exclude = ('server', 'user', 'date')

top/views.py
import logging
from datetime import timedelta

from allauth.account.decorators import verified_email_required
from django.conf import settings
from django.contrib import messages
from django.contrib.postgres.search import SearchVector
from django.core.mail import EmailMultiAlternatives
from django.core.paginator import Paginator
from django.db.models import Avg
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from top.forms import CommentForm, ContactForm, ServerForm
from .models import Server, Vote, Comment, Tag, MinecraftStats

logger = logging.getLogger(__name__)


def contact(request):
    email = ""
    asunto = ""
    mensaje = ""
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            ip = get_client_ip(request)
            email = contact_form.cleaned_data['email']
            asunto = contact_form.cleaned_data['subject']
            mensaje = contact_form.cleaned_data['message']
            captcha = contact_form.cleaned_data['captcha']
            if isValidCaptcha(captcha):
                to = settings.SITE_EMAIL
                html_content = "Formulario de contacto:<br><br><b>De: </b>%s<br><b>IP:</b> %s<br><b>Asunto:</b>%s<br><b>Mensaje:</b><br>%s" % (
                email, ip, asunto, mensaje)
                msg = EmailMultiAlternatives('Formulario de Contacto', html_content, settings.SITE_EMAIL, [to])
                msg.attach_alternative(html_content, 'text/html')
                try:
                    msg.send()
                    feedback = _("Message sent!")
                    messages.add_message(request, messages.SUCCESS, feedback)
                except Exception:
                    feedback = _("Error sending message :(")
                    messages.add_message(request, messages.ERROR, feedback)
                    logger.error('Error sending mail!')
    else:
        contact_form = ContactForm()

    context = {
        'form': contact_form,
        'email': email,
        'subject': asunto,
        'message': mensaje
    }
    return render(request, 'top/contact.html', context)


def isValidCaptcha(code):
    return True
    secret = settings.RECAPTCHA_PRIVATE_KEY
    url = 'https://www.google.com/recaptcha/api/siteverify'
    data = {'secret': secret, 'response': code}
    response = urllib2.urlopen(url, urllib.urlencode(data))
    result = json.load(response)
    print(result)
    if result['success']:
        if result['score'] > 0.5:
            return True
    return False


def index(request):
    latest_servers_list = Server.objects.recent()[:10]
    voted_servers_list = Server.objects.monthly_votes()[:10]
    premium_servers_list = Server.objects.active_premium().order_by('?')[:10]
    context = {
        'latest_servers_list': latest_servers_list,
        'voted_servers_list': voted_servers_list,
        'premium_servers_list': premium_servers_list,
    }
    return render(request, 'top/index.html', context)


def monthTop(request, pagenum=1):
    pagenum = int(pagenum)  # importante, debe ser int
    all_servers = Server.objects.monthly_votes()
    servers = Paginator(all_servers, 10)
    if pagenum <= servers.num_pages:
        thispage = servers.page(pagenum)
        i = (pagenum - 1) * 10 + 1
        for server in thispage:
            server.rank = i
            i += 1
        context = {
            'servers': thispage,
            'page': pagenum,
            'totalPages': servers.page_range[-1],
            'pagination': pagination(pagenum, servers.page_range)
        }
        return render(request, 'top/month.html', context)
    else:
        raise Http404


def yearTop(request, pagenum=1):
    pagenum = int(pagenum)  # importante, debe ser int
    all_servers = Server.objects.yearly_votes()
    servers = Paginator(all_servers, 10)
    thispage = servers.page(pagenum)
    i = (pagenum - 1) * 10 + 1
    for server in thispage:
        server.rank = i
        i += 1
    context = {
        'servers': thispage,
        'page': pagenum,
        'totalPages': servers.page_range[-1],
        'pagination': pagination(pagenum, servers.page_range)
    }
    return render(request, 'top/year.html', context)


def globalTop(request, pagenum=1):
    pagenum = int(pagenum)  # importante, debe ser int
    all_servers = Server.objects.total_votes()
    servers = Paginator(all_servers, 10)
    thispage = servers.page(pagenum)
    i = (pagenum - 1) * 10 + 1
    for server in thispage:
        server.rank = i
        i += 1
    context = {
        'servers': thispage,
        'page': pagenum,
        'totalPages': servers.page_range[-1],
        'pagination': pagination(pagenum, servers.page_range)
    }
    return render(request, 'top/global.html', context)


def recentTop(request, pagenum=1):
    pagenum = int(pagenum)  # importante, debe ser int
    all_servers = Server.objects.recent()
    servers = Paginator(all_servers, 10)
    thispage = servers.page(pagenum)
    i = (pagenum - 1) * 10 + 1
    for server in thispage:
        server.rank = i
        i += 1
    context = {
        'servers': thispage,
        'page': pagenum,
        'totalPages': servers.page_range[-1],
        'pagination': pagination(pagenum, servers.page_range)
    }
    return render(request, 'top/recent.html', context)


def popularTop(request, pagenum=1):
    pagenum = int(pagenum)  # importante, debe ser int
    servers_by_popularity = Server.objects.popular()
    servers = Paginator(servers_by_popularity, 10)
    thispage = servers.page(pagenum)
    i = (pagenum - 1) * 10 + 1
    for server in thispage:
        server.rank = i
        i += 1
    context = {
        'servers': thispage,
        'page': pagenum,
        'totalPages': servers.page_range[-1],
        'pagination': pagination(pagenum, servers.page_range)
    }
    return render(request, 'top/popular.html', context)


def serverSearch(request):
    query = request.GET.get('q', None)
    if query:
        if settings.DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
            servers = Server.objects.filter(name__icontains=query)
            if len(servers) == 0:
                servers = Server.objects.annotate(
                    search = SearchVector('name') + SearchVector('description')
                ).filter(search=query)
        else:
            servers = Server.objects.filter(name__icontains=query)

    context = {
        'query': query,
        'servers': servers if servers else [],
    }
    return render(request, 'top/search.html', context)


def server(request, server_id):
    try:
        server = Server.objects.get(pk=server_id)
        slug = slugify(server.name)
        return HttpResponseRedirect('/top/server/{}/{}/'.format(server.id, slug))
    except Server.DoesNotExist:
        raise Http404


def serverWithSlug(request, server_id, slug=""):
    try:
        server = Server.objects.get(pk=server_id)
        comments = Comment.objects.filter(server=server).order_by('-date')
        avg_events = comments.aggregate(Avg('events'));
        avg_support = comments.aggregate(Avg('support'));
        avg_uptime = comments.aggregate(Avg('uptime'));
    except Server.DoesNotExist:
        raise Http404

    current_slug = slugify(server.name)
    if current_slug != slug:
        return HttpResponseRedirect('/top/server/{}/{}/'.format(server.id, current_slug))

    # update visits
    server.visits += 1
    server.save(update_image=False)

    tags = server.tags.all()
    context = {
        'server': server,
        'tags': tags,
        'comments': comments,
        'avg_events': 0 if avg_events['events__avg'] is None else avg_events['events__avg'],
        'avg_support': 0 if avg_support['support__avg'] is None else avg_support['support__avg'],
        'avg_uptime': 0 if avg_uptime['uptime__avg'] is None else avg_uptime['uptime__avg'],
        'description': server.name,
        'keywords': server.name,
        'form': CommentForm(),
    }
    return render(request, 'top/server.html', context)


def editServer(request, server_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/accounts/login/')

    try:
        server = Server.objects.get(pk=server_id)
    except Server.DoesNotExist:
        raise Http404

    if not server.owner == request.user:
        return HttpResponseRedirect('/top/server/%s/' % (server_id))

    if request.method == "POST":
        form = ServerForm(request.POST, request.FILES, instance=server)
        if form.is_valid():
            server = form.save()
            if ('tags_field' in request.POST):
                if not request.POST['tags_field'] == '':
                    tag_ids = request.POST['tags_field'].split(',')
                    server.tags.clear()
                    if len(tag_ids) > 0:
                        tag_ids = [int(x) for x in tag_ids]
                        for t in tag_ids:
                            # check if tag exists
                            if Tag.objects.filter(id=t).count() > 0:
                                server.tags.add(t)
                    server.save()
                else:
                    server.tags.clear()
                    server.save()

            messages.add_message(request, messages.SUCCESS, _("Server edited"))
            return HttpResponseRedirect('/top/server/{}/'.format(server.id))
        else:
            messages.add_message(request, messages.ERROR, _("[Error] Incorrect data"))
    else:
        form = ServerForm(instance=server)

    server_tags = server.tags.all()
    tags = []
    for tag in Tag.objects.all():
        tags.append({
            'id': tag.id,
            'name': tag.name,
            'active': tag in server_tags
        })

    context = {
        'form': form,

top/templates/top/addServer.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %} {% trans "Add server" %} - {{ SITE_NAME }}{% endblock %}

{% block main %}
<div class="row-fluid well">
	<h1>{% trans "Add server" %}</h1>
	<p>{% trans "Let players find your server. Describe what kind of server it is and what makes it the best of them all!" %}</p>
	{% if message %}
		<div class="alert">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<div class="text-warning"><strong>{% trans "Message" %}: </strong>{{ message }}</div>
		</div>
	{% endif %}
	<form action="" method="POST" style="margin:0" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" class="btn btn-primary" value="{% trans "Create" %}"/>
	</form>
</div>
{% endblock %}

{% block scripts%}
{% endblock %}

top/templates/top/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Contact" %} - {{ SITE_NAME }}{% endblock %}

{% block heading %}
    {% include "top/promoHeader.html" %}
{% endblock %}

{% block main %}
<div class="row-fluid well">
	<h1>{% trans "Contact us" %}</h1>
	<p>{% trans "Want to tell us something? Any error you found in the rankings? Wrong server information?" %}</p>
	<p>{% trans "You can send us a message with the following form" %}:</p>

	<form action="." method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		<input class="btn btn-primary" type="submit" value="{% trans "Send" %}" />
	</form>
</div>

<script src="https://www.google.com/recaptcha/api.js?render={{ RECAPTCHA_PUBLIC_KEY }}"></script>
<script>
grecaptcha.ready(function() {
    grecaptcha.execute('{{ RECAPTCHA_PUBLIC_KEY }}', {action: 'homepage'}).then(function(token) {
       $('#id_captcha').val(token);
    });
});
</script>

{% endblock %}

top/templates/top/editServer.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %} {% trans "Edit server" %} - {{ SITE_NAME }}{% endblock %}

{% block main %}
<div class="row-fluid well">
	<h2>{% trans "Edit server" %}</h2>
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		<div class="form-group">
			<label>{% trans "Tags" %}</label>
			<input type="hidden" name="tags_field" id="tags_field" value=""/>
			<ul id="tag-selector">
				{% for tag in tags %}
					<li><a href="#" data-tag-id="{{ tag.id }}" data-tag-active="{{ tag.active|lower }}" class="badge badge-pill {% if tag.active %}badge-success{% else %}badge-secondary{% endif %}">{% autoescape off %}{{ tag.name }}{% endautoescape %}</a></li>
				{% endfor %}
			</ul>
		</div>
		<input type="submit" class="btn btn-primary" value="{% trans "Save changes" %}"/>
		<a class="btn btn-secondary" href="{% url 'server' server.id %}">{% trans "View" %}</a>
	</form>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
	$(document).ready(function() {
		$("#tag-selector .badge").click(function (e) {
			if ($(this).data('tag-active')) {
				$(this).data('tag-active', false);
				$(this).removeClass('badge-success');
				$(this).addClass('badge-secondary');
			} else {
				$(this).data('tag-active', true);
				$(this).removeClass('badge-secondary');
				$(this).addClass('badge-success');
			}

			var activeTagIds = [];
			$("#tag-selector .badge").each(function() {
				if ($(this).data('tag-active')) {
					activeTagIds.push($(this).data('tag-id'));
				}
			});
			$('#tags_field').val(activeTagIds.join(','));

			e.preventDefault();
		});
	});
</script>
{% endblock %}

top/templates/top/global.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Global top" %} - {{ SITE_NAME }}{% endblock %}

{% block heading %}
    {% include "top/promoHeader.html" %}
{% endblock %}

{% block main %}
<div class="row-fluid well">
	<h1>{% blocktrans %}Best {{ GAME_NAME }} servers overall{% endblocktrans %}</h1>
	<p>{% blocktrans %}Overall ranking of most voted {{ GAME_NAME }} servers{% endblocktrans %}</p>
	{% if servers %}
		<table class="table table-striped">
			<thead><tr><th>{% trans "Top" %}</th><th>{% trans "Server" %}</th><th class="text-center">{% trans "Total votes" %}</th></tr></thead>
		{% for server in servers %}
			<tr {% if server.is_premium %}class="row-premium" title="{% trans "Premium Server" %}"{% endif %}>
				<td style="text-align:center">
				{% if server.rank == 1 %}<img src="/static/top/img/gold.png" alt="gold"/>{% endif %}
				{% if server.rank == 2 %}<img src="/static/top/img/silver.png" alt="silver"/>{% endif %}
				{% if server.rank == 3 %}<img src="/static/top/img/bronze.png" alt="bronze"/>{% endif %}
				{% if server.rank > 3 %}{{ server.rank }}{% endif %}
				</td>
				<td><a href="/top/server/{{ server.id }}/">{{ server.name }}</a></td>
				<td class="text-center"><span class="badge badge-info">{{ server.votes }}</span></td>
			</tr>
		{% endfor %}
		</table>
		<div class="d-flex justify-content-center">
			<ul class="pagination">
				{% if page > 1 %}
				<li class="page-item"><a class="page-link" href="/top/global/page-{{ page|add:-1 }}/" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
				{% else %}
				<li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
				{% endif %}

				{% for p in pagination.pages %}
					{% if p == pagination.current_page %}
					<li class="page-item active"><a class="page-link" href="/top/global/page-{{ p }}/">{{ p }}</a></li>
					{% elif p == -1 %}
					<li class="page-item disabled"><a class="page-link" href="#">...</a></li>
					{% else %}
					<li class="page-item"><a class="page-link" href="/top/global/page-{{ p }}/">{{ p }}</a></li>
					{% endif %}
				{% endfor %}

				{% if page < totalPages %}
				<li class="page-item"><a class="page-link" href="/top/global/page-{{ page|add:1 }}/" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
				{% else %}
				<li class="page-item disabled"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
				{% endif %}
			</ul>
		</div>
	{% else %}
		<p>No servers are available.</p>
	{% endif %}
</div>
{% endblock %}

top/templates/top/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Home" %} - {{ SITE_NAME }}{% endblock %}

{% block heading %}
    <div class="row">
        <div class="col-12">
            <div class="alert alert-success" role="alert">
                <a href="{% url 'popularTop' %}" class="alert-link">{% blocktrans %}NEW! The most popular {{ GAME_NAME }} servers now{% endblocktrans %}</a>
            </div>
        </div>
    </div>
    {% include "top/promoHeader.html" %}
    <div class="row-fluid d-none">
        <div class="col-12">
            <a href="/vote4coins/"><div class="alert alert-success" style="font-size:1.2em;">
                <strong>New!</strong> Vote4Coins system, reward your users when they vote on {{ SITE_NAME }}. Click here for more info and get the PHP script.
            </div></a>
        </div>
    </div>
{% endblock %}

{% block main %}
<div class="row" style="margin:0">
	{% if voted_servers_list %}
        <div class="col-12 ranking-container">
            <h2 class="text-center"><a href="/top/month/">{% blocktrans %}Best {{ GAME_NAME }} servers this month{% endblocktrans %}</a></h2>
            {% for server in voted_servers_list %}
                <div class="well{% if server.is_premium %} row-premium{% endif %}" style="position:relative;">
                    {% if server.is_premium %}
                        <span style="position: absolute; top:-2px; left:8px;"><img src="{% static 'top/img/premium.png' %}" alt="premium"/></span>
                    {% endif %}

                    <div class="row">
                        <div class="col-3">
                            {% if forloop.counter == 1 %}<img src="{% static 'top/img/gold.png' %}" alt="gold"/>{% endif %}
                            {% if forloop.counter == 2 %}<img src="{% static 'top/img/silver.png' %}" alt="silver"/>{% endif %}
                            {% if forloop.counter == 3 %}<img src="{% static 'top/img/bronze.png' %}" alt="bronze"/>{% endif %}
                            {% if forloop.counter > 3 %}
                                {% if server.is_premium %}
                                    <img src="/media/top/img/star.png" alt="premium"/>
                                {% else %}
                                    <strong>Top #{{ forloop.counter }}</strong>
                                {% endif %}
                            {% endif %}
                        </div>
                        <div class="col-6 text-center" style="font-size: 1.1em;">
                            {% for tag in server.tags.all %}
                            {% ifequal tag.name 'Español' %}<span><img style="margin: -3px 5px 0 0" src="{% static 'top/img/lang/es.gif' %}"/></span>{% endifequal %}
                            {% ifequal tag.name 'Deutsch' %}<span><img style="margin: -3px 5px 0 0" src="{% static 'top/img/lang/de.gif' %}"/></span>{% endifequal %}
                            {% ifequal tag.name 'English' %}<span><img style="margin: -3px 5px 0 0" src="{% static 'top/img/lang/us.gif' %}"/></span>{% endifequal %}
                            {% ifequal tag.name 'Italiano' %}<span><img style="margin: -3px 5px 0 0" src="{% static 'top/img/lang/it.gif' %}"/></span>{% endifequal %}
                            {% endfor %}
                            <a href="/top/server/{{ server.id }}/"><strong>{{ server.name }}</strong></a>
                        </div>
                        <div class="col-3 votes" style="text-align:center;">
                            <span class="badge {% if server.is_premium %}badge-success{% else %}badge-info{% endif %}">
                                {{ server.month_votes }} {% trans "Votes" %}
                            </span>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <p class="text-center">
                            <a href="/top/server/{{ server.id }}/"><img class="img-fluid" src="/media/{{ server.image }}" alt="{{ server.name }}-image" style="max-height:80px;"/></a>
                        </p>
                    </div>
                </div>

                <div class="clearfix"></div>

            {% endfor %}
            <div class="row-fluid">
                <div class="col-12 text-center">
                    <a class="btn btn-info" href="/top/month">{% trans "View more" %}</a>
                </div>
            </div>
        </div>
	{% else %}
		<div class="col-6">
			<h5 class="text-center">{% trans "Monthly top" %}</h5>
			<p>{% trans "No servers" %}</p>
		</div>
	{% endif %}
</div>

<hr class="dark" />

<div class="well row" style="margin:0">
	{% if latest_servers_list %}
		<div class="col-12">
			<h2 class="text-center">{% blocktrans %}New {{ GAME_NAME }} servers{% endblocktrans %}</h2>
			<table class="table table-striped ranking">
				<thead><tr><th></th><th>{% trans "Server" %}</th><th class="text-center">{% trans "Votes" %}</th></tr></thead>
			{% for server in latest_servers_list %}
				<tr {% if server.is_premium %}class="row-premium" title="{% trans "Premium Server" %}"{% endif %}>
					<td class="text-center">
                        {% if server.is_premium %}
                            <img src="{% static 'top/img/star.png' %}" alt="premium"/>
                        {% else %}
                            <img src="{% static 'top/img/time.png' %}" alt="recent"/>
                        {% endif %}
                    </td>
					<td><a href="/top/server/{{ server.id }}/">{{ server.name }}</a></td>
					<td class="text-center"><span class="badge badge-info">{{ server.votes }}</span></td>
				</tr>
			{% endfor %}
			</table>
		</div>
	{% else %}
		<div class="col-6">
			<h5 class="text-center">{% trans "Latest added" %}</h5>
			<p>{% trans "No servers" %}</p>
		</div>
	{% endif %}
</div>
	<div class="clearfix"></div>
{% endblock %}

top/templates/top/month.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Monthly Top" %} - {{ SITE_NAME }}{% endblock %}

{% block heading %}
    {% include "top/promoHeader.html" %}
{% endblock %}

{% block main %}
<div class="row-fluid well">
	<h1>{% blocktrans %}Best {{ GAME_NAME }} servers of the month{% endblocktrans %}</h1>
	<p>{% blocktrans %}Most voted {{ GAME_NAME }} servers of the last 30 days{% endblocktrans %}</p>
	{% if servers %}
		<table class="table table-striped">
			<thead><tr><th>{% trans "Top" %}</th><th>{% trans "Server" %}</th><th class="text-center">{% trans "Votes this month" %}</th></tr></thead>
		{% for server in servers %}
			<tr {% if server.is_premium %}class="row-premium" title="{% trans "Premium Server" %}"{% endif %}>
				<td style="text-align:center">
				{% if server.rank == 1 %}<img src="/static/top/img/gold.png" alt="gold"/>{% endif %}
				{% if server.rank == 2 %}<img src="/static/top/img/silver.png" alt="silver"/>{% endif %}
				{% if server.rank == 3 %}<img src="/static/top/img/bronze.png" alt="bronze"/>{% endif %}
				{% if server.rank > 3 %}{{ server.rank }}{% endif %}
				</td>
				<td><a href="/top/server/{{ server.id }}/">{{ server.name }}</a></td>
				<td class="text-center"><span class="badge badge-info">{{ server.month_votes }}</span></td>
			</tr>
		{% endfor %}
		</table>
		<div class="d-flex justify-content-center">
			<ul class="pagination">
				{% if page > 1 %}
				<li class="page-item"><a class="page-link" href="/top/month/page-{{ page|add:-1 }}/" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
				{% else %}
				<li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
				{% endif %}

				{% for p in pagination.pages %}
					{% if p == pagination.current_page %}
					<li class="page-item active"><a class="page-link" href="/top/month/page-{{ p }}/">{{ p }}</a></li>
					{% elif p == -1 %}
					<li class="page-item disabled"><a class="page-link" href="#">...</a></li>
					{% else %}
					<li class="page-item"><a class="page-link" href="/top/month/page-{{ p }}/">{{ p }}</a></li>
					{% endif %}
				{% endfor %}

				{% if page < totalPages %}
				<li class="page-item"><a class="page-link" href="/top/month/page-{{ page|add:1 }}/" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
				{% else %}
				<li class="page-item disabled"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
				{% endif %}
			</ul>
		</div>
	{% else %}
		<p>{% trans "No servers" %}</p>
	{% endif %}
</div>
{% endblock %}